package javaassignment10;


import javax.swing.JApplet;
import javax.swing.JFrame;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Owner
 */
public class NewJPanel1 extends javax.swing.JPanel {    float rate=0,time=0,pr=0,SI=0,PI=0;

    /**
     * Creates new form NewJPanel1
     */
    public NewJPanel1() {
        initComponents();
    }
    public static void main(String[] args) {
        JFrame jf=new JFrame();
        jf.setContentPane(new NewJPanel1());
        jf.setBounds(10, 10, 200, 200);
        jf.setVisible(true);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();

        setLayout(null);

        jLabel1.setText("PRINCIPLE");
        add(jLabel1);
        jLabel1.setBounds(40, 30, 60, 10);
        add(jTextField1);
        jTextField1.setBounds(130, 20, 130, 40);

        jLabel2.setText("RATE");
        add(jLabel2);
        jLabel2.setBounds(40, 90, 34, 14);
        add(jTextField2);
        jTextField2.setBounds(130, 80, 130, 40);

        jLabel3.setText("TIME");
        add(jLabel3);
        jLabel3.setBounds(40, 160, 24, 14);
        add(jTextField3);
        jTextField3.setBounds(130, 150, 130, 40);

        jButton1.setText("SI");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ABC(evt);
            }
        });
        add(jButton1);
        jButton1.setBounds(40, 200, 43, 23);

        jButton2.setText("PI");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ABC(evt);
            }
        });
        add(jButton2);
        jButton2.setBounds(180, 200, 43, 23);

        jLabel4.setText("INTEREST");
        add(jLabel4);
        jLabel4.setBounds(40, 240, 60, 20);
        add(jTextField4);
        jTextField4.setBounds(130, 230, 130, 40);
    }// </editor-fold>//GEN-END:initComponents

    private void ABC(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ABC
       pr=Float.parseFloat(jTextField1.getText());
        rate=Float.parseFloat(jTextField2.getText());
        time=Float.parseFloat(jTextField3.getText());
        SI=(float)pr*rate*time/100;

        PI=pr*(float)Math.pow((1+rate/100), time);
        if(evt.getActionCommand().equals("SI")){
        jTextField4.setText(""+SI);
        }
        if(evt.getActionCommand().equals("PI")){
        jTextField4.setText(""+PI);
        } 
    }//GEN-LAST:event_ABC

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    // End of variables declaration//GEN-END:variables
}
