/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package javaassignment10;

import java.awt.Font;
import java.awt.Label;
import javax.swing.JFrame;

/**
 *
 * @author Owner
 */
public class NewJPanel4 extends javax.swing.JPanel {

    /**
     * Creates new form NewJPanel4
     */
    public NewJPanel4() {
        initComponents();
    }
    public static void main(String[] args) {
        JFrame jf=new JFrame();
        jf.setContentPane(new NewJPanel4());
        jf.setBounds(10, 10, 200, 200);
        jf.setVisible(true);
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jRadioButton3 = new javax.swing.JRadioButton();
        jCheckBox1 = new javax.swing.JCheckBox();
        jCheckBox2 = new javax.swing.JCheckBox();
        jCheckBox3 = new javax.swing.JCheckBox();

        setLayout(null);

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("FONT");
        add(jLabel1);
        jLabel1.setBounds(2, 11, 390, 30);

        buttonGroup1.add(jRadioButton1);
        jRadioButton1.setText("LEFT");
        jRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton1ActionPerformed(evt);
            }
        });
        add(jRadioButton1);
        jRadioButton1.setBounds(60, 100, 80, 23);

        buttonGroup1.add(jRadioButton2);
        jRadioButton2.setText("CENTRE");
        jRadioButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton1ActionPerformed(evt);
            }
        });
        add(jRadioButton2);
        jRadioButton2.setBounds(145, 100, 90, 23);

        buttonGroup1.add(jRadioButton3);
        jRadioButton3.setText("RIGHT");
        jRadioButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton1ActionPerformed(evt);
            }
        });
        add(jRadioButton3);
        jRadioButton3.setBounds(260, 100, 90, 23);

        jCheckBox1.setText("BOLD");
        jCheckBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox1ActionPerformed(evt);
            }
        });
        add(jCheckBox1);
        jCheckBox1.setBounds(31, 150, 110, 23);

        jCheckBox2.setText("ITALIC");
        jCheckBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox2ActionPerformed(evt);
            }
        });
        add(jCheckBox2);
        jCheckBox2.setBounds(160, 150, 80, 23);

        jCheckBox3.setText("PLAIN");
        jCheckBox3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox3ActionPerformed(evt);
            }
        });
        add(jCheckBox3);
        jCheckBox3.setBounds(260, 150, 90, 23);
    }// </editor-fold>//GEN-END:initComponents

    private void jRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton1ActionPerformed
      
        if(jRadioButton1.isSelected()){
        jLabel1.setHorizontalAlignment(Label.LEFT);
        }
       else if(jRadioButton2.isSelected()){
        jLabel1.setHorizontalAlignment(Label.CENTER);
        }
       else if(jRadioButton3.isSelected()){
        jLabel1.setHorizontalAlignment(Label.RIGHT);
        }
       else{
       jLabel1.setHorizontalAlignment(Label.CENTER);
        }
    }//GEN-LAST:event_jRadioButton1ActionPerformed

    private void jCheckBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox2ActionPerformed
jLabel1.setFont(new Font("Times New Roman", Font.ITALIC, 24));
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox2ActionPerformed

    private void jCheckBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox1ActionPerformed
if(jCheckBox1.isSelected()){
jLabel1.setFont(new Font("Times New Roman", Font.BOLD, 24));
}
    }//GEN-LAST:event_jCheckBox1ActionPerformed

    private void jCheckBox3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox3ActionPerformed
jLabel1.setFont(new Font("Times New Roman", Font.PLAIN, 24));
    
    }//GEN-LAST:event_jCheckBox3ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JCheckBox jCheckBox2;
    private javax.swing.JCheckBox jCheckBox3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton3;
    // End of variables declaration//GEN-END:variables
}
