/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package javaassignment10;
import javax.swing.JFrame;

/**
 *
 * @author Owner
 */
public class NewJPanel2 extends javax.swing.JPanel {

        float radius,area;
    /**
     * Creates new form NewJPanel2
     */
    public NewJPanel2() {
        initComponents();
    }
    public static void main(String[] args) {
        JFrame jf=new JFrame();
        jf.setContentPane(new NewJPanel2());
        jf.setBounds(10, 10, 200, 200);
        jf.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();

        setLayout(null);

        jLabel1.setText("RADIUS");
        add(jLabel1);
        jLabel1.setBounds(61, 32, 40, 20);

        jLabel2.setText("AREA");
        add(jLabel2);
        jLabel2.setBounds(70, 120, 34, 14);
        add(jTextField1);
        jTextField1.setBounds(140, 30, 160, 50);
        add(jTextField2);
        jTextField2.setBounds(140, 110, 160, 50);

        jButton1.setText("CALCULATE");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1);
        jButton1.setBounds(60, 180, 310, 50);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
radius=Float.parseFloat(jTextField1.getText());

        area=(float)((Math.PI)*Math.pow(radius, 2));
//circumference=(float)(2*(Math.PI)*radius);
if(evt.getActionCommand().equals("CALCULATE")){
    jTextField2.setText(""+area);
}// jTextField3.setText(""+circumference);        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    // End of variables declaration//GEN-END:variables
}
